stages:
  - build
  - test
  - deploy

.build_template: &build_definition
  stage: build
  artifacts:
    paths:
      - build/
      - .lock-waf*

.test_template: &test_definition
  stage: test
  artifacts:
    paths:
      - build/coverage


arm:
  <<: *build_definition
  image: drobilla/debian-stretch
  script: python ./waf configure build -dsT
  variables:
    CC: "arm-linux-gnueabihf-gcc"
    CXX: "arm-linux-gnueabihf-g++"

test:arm:
  <<: *test_definition
  image: drobilla/debian-stretch
  script: python ./waf test --wrapper=qemu-arm
  dependencies:
    - arm


aarch64:
  <<: *build_definition
  image: drobilla/debian-stretch
  script: python ./waf configure build -dsT
  variables:
    CC: "aarch64-linux-gnu-gcc"
    CXX: "aarch64-linux-gnu-g++"

test:aarch64:
  <<: *test_definition
  image: drobilla/debian-stretch
  script: python ./waf test --wrapper=qemu-aarch64
  dependencies:
    - aarch64


amd64_dbg:
  <<: *build_definition
  image: drobilla/debian-stretch
  script: python ./waf configure build -dsT

test:amd64_dbg:
  <<: *test_definition
  image: drobilla/debian-stretch
  script: python ./waf test
  dependencies:
    - amd64_dbg


amd64_rel:
  <<: *build_definition
  image: drobilla/debian-stretch
  script: python ./waf configure build -sT

test:amd64_rel:
  <<: *test_definition
  image: drobilla/debian-stretch
  script: python ./waf test
  dependencies:
    - amd64_rel


amd64_static:
  <<: *build_definition
  image: drobilla/debian-stretch
  script: python ./waf configure build -sT --no-posix --static-progs

test:amd64_static:
  <<: *test_definition
  image: drobilla/debian-stretch
  script: python ./waf test
  dependencies:
    - amd64_static


mac_dbg:
  <<: *build_definition
  script: python ./waf configure build -dsT --no-coverage
  tags:
    - macos

test:mac_dbg:
  <<: *test_definition
  script: python ./waf test
  dependencies:
    - mac_dbg
  tags:
    - macos


mac_rel:
  <<: *build_definition
  script: python ./waf configure build -sT --no-coverage
  tags:
    - macos

test:mac_rel:
  <<: *test_definition
  script: python ./waf test
  dependencies:
    - mac_rel
  tags:
    - macos


win_dbg:
  <<: *build_definition
  script:
    - python ./waf configure build -dT --no-coverage
  tags:
    - windows

test:win_dbg:
  <<: *test_definition
  script: python ./waf test
  dependencies:
    - win_dbg
  tags:
    - windows


win_rel:
  <<: *build_definition
  script: python ./waf configure build -T --no-coverage
  tags:
    - windows

test:win_rel:
  <<: *test_definition
  script: python ./waf test
  dependencies:
    - win_rel
  tags:
    - windows


pages:
  stage: deploy
  script: mv build/coverage/ public/
  dependencies:
    - test:amd64_dbg
  artifacts:
    expire_in: 30 days
    paths:
      - public
  only:
    - master
